name: Pipeline for Dev deployment

on:
  push:
    branches:
      - "sdev*"
    paths:
      - '.github/workflows/**'
      - 'tf-modules/**'
      - 'environments/development/*'

jobs:
  deploy:
    uses: ./.github/workflows/aws-deploy.yml
    with:
      gh_environment: "dev"
    secrets: inherit
