on:
    pull_request:
      types: [opened, synchronize, closed]
    push:
      branches:
        - main
jobs:
    infracost-pull-request-checks:
        name: Infracost Pull Request Checks
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Setup Infracost
              uses: infracost/actions/setup@v3
              with:
                  api_key: ${{ secrets.INFRACOST_API_KEY }}
            # Checkout the base branch of the pull request (e.g. main/master).
            - name: Checkout base branch
              uses: actions/checkout@v4
              with:
                ref: '${{ github.event.pull_request.base.ref }}'
            # Generate Infracost JSON file as the baseline.
            - name: Generate Infracost cost estimate baseline
              run: |
                export INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}
                infracost breakdown --path=environments/development \
                            --format=json \
                            --out-file=/tmp/infracost-base.json
                echo "Check is done"
            # Checkout the pull request branch.
            - name: Checkout pull request branch
              uses: actions/checkout@v4
              with:
                ref: '${{ github.event.pull_request.head.ref }}'
            # Generate Infracost diff and save it to a JSON file
            - name: Generate Infracost diff
              run: |
                export INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}
                infracost diff --path=environments/development \
                            --format=json \
                            --show-skipped \
                            --compare-to=/tmp/infracost-base.json \
                            --out-file=/tmp/infracost.json 
            # Generate HTML report
            - name: Generate Infracost HTML report
              run: |
                export INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}
                infracost output --path /tmp/infracost.json --show-skipped --format html --out-file report.html

## infracost
#--format=json \
#--out-file=/tmp/infracost-base.json